# Server
server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB
# 配置数据源信息
spring:
  profiles:
    active: dev # 激活dev配置 一些账户等
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000 # 文件大小 500 KB
      max-request-size: 512000 # 文件请求大小 500 KB

# mybatis 配置
mybatis:
  type-aliases-package: com.sin.pojo # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 通用 Mapper 配置
mapper:
  mappers: com.example.oversell.tkmapper.TKMapper
  not-empty: false # 在进行数据库操作的时候，判断表达式 val!=null, 是否追加 username != ''
  identity: MYSQL